=== TheXankriegor/LunaCompat/LunaCompat/PartSyncSchema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="ModuleDefinition">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="1" name="Fields">
					<xs:complexType>
						<xs:sequence>
							<xs:element maxOccurs="unbounded" name="FieldDefinition">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="FieldName" >
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:pattern value="^(?!\s*$).+" />
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element minOccurs="0" name="MaxIntervalInMs" type="xs:string" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
					<xs:unique name="UniqueFieldName">
						<xs:selector xpath="FieldDefinition" />
						<xs:field xpath="FieldName" />
					</xs:unique>
				</xs:element>
				<xs:element minOccurs="0" maxOccurs="1" name="Methods">
					<xs:complexType>
						<xs:sequence>
							<xs:element maxOccurs="unbounded" name="MethodDefinition">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="MethodName" >
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:pattern value="^(?!\s*$).+" />
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element minOccurs="0" name="MaxIntervalInMs" type="xs:string" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
					<xs:unique name="UniqueMethodName">
						<xs:selector xpath="MethodDefinition" />
						<xs:field xpath="MethodName" />
					</xs:unique>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
		
	</xs:element>
</xs:schema>

=== TheXankriegor/LunaCompat/LunaCompat/XML_COMPAT/KerbalActuators/WBIMagnetController.xml
<?xml version="1.0"?>
<ModuleDefinition xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:schemaLocation="luna:schema ../../PartSyncSchema.xsd">
	<Fields>
		<FieldDefinition>
			<FieldName>magnetActivated</FieldName>
		</FieldDefinition>
	</Fields>
	<Methods>
		<MethodDefinition>
			<MethodName>ActivateMagnet</MethodName>
		</MethodDefinition>
		<MethodDefinition>
			<MethodName>DeactivateMagnet</MethodName>
		</MethodDefinition>
	</Methods>
</ModuleDefinition>

=== TheXankriegor/LunaCompat/LunaCompat/XML_COMPAT/WildBlueTools/WBIOmniConverter.xml
<?xml version="1.0"?>
<ModuleDefinition xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:schemaLocation="luna:schema ../../PartSyncSchema.xsd">
	<Fields>
		<FieldDefinition>
			<FieldName>currentTemplateName</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>cycleStartTime</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>progress</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>lastAttempt</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>enableBackgroundProcessing</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>ID</FieldName>
		</FieldDefinition>
	</Fields>
</ModuleDefinition>

=== TheXankriegor/LunaCompat/LunaCompat/XML_COMPAT/ProceduralParts/ProceduralShapeHollowPill.xml
<?xml version="1.0"?>
<ModuleDefinition xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:schemaLocation="luna:schema ../../PartSyncSchema.xsd">
	<Fields>
		<FieldDefinition>
			<FieldName>innerDiameter</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>outerDiameter</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>length</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>fillet</FieldName>
		</FieldDefinition>
	</Fields>
</ModuleDefinition>

=== TheXankriegor/LunaCompat/LunaCompat/XML_COMPAT/Interstellar/FNRadiator.xml
<?xml version="1.0"?>
<ModuleDefinition xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:schemaLocation="luna:schema ../../PartSyncSchema.xsd">
	<Fields>
		<FieldDefinition>
			<FieldName>radiatorInit</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>showRetractButton</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>showControls</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>currentRadTemp</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>clarifyFunction</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>radiatorIsEnabled</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>isAutomated</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>pivotEnabled</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>preventShieldedDeploy</FieldName>
		</FieldDefinition>
	</Fields>
	<Methods>
		<MethodDefinition>
			<MethodName>DeployRadiator</MethodName>
		</MethodDefinition>
		<MethodDefinition>
			<MethodName>RetractRadiator</MethodName>
		</MethodDefinition>
	</Methods>
</ModuleDefinition>

=== TheXankriegor/LunaCompat/LunaCompat/XML_COMPAT/IR-ConnectionSystem/ModuleIRGF.xml
<?xml version="1.0"?>
<ModuleDefinition xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:schemaLocation="luna:schema ../../PartSyncSchema.xsd">
	<Fields>
		<FieldDefinition>
			<FieldName>crossfeed</FieldName>
		</FieldDefinition>
	</Fields>
	<Methods>
		<MethodDefinition>
			<MethodName>TogglePort</MethodName>
		</MethodDefinition>
		<MethodDefinition>
			<MethodName>EnableXFeed</MethodName>
		</MethodDefinition>
		<MethodDefinition>
			<MethodName>DisableXFeed</MethodName>
		</MethodDefinition>
	</Methods>
</ModuleDefinition>

=== TheXankriegor/LunaCompat/LunaCompat/XML_COMPAT/WildBlueTools/WBILight.xml
<?xml version="1.0"?>
<ModuleDefinition xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:schemaLocation="luna:schema ../../PartSyncSchema.xsd">
	<Fields>
		<FieldDefinition>
			<FieldName>ecRequired</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>red</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>green</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>blue</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>level</FieldName>
		</FieldDefinition>
	</Fields>
</ModuleDefinition>

=== TheXankriegor/LunaCompat/LunaCompat/XML_COMPAT/WildBlueCore/WBIModuleResourceConverterExtended.xml
<?xml version="1.0"?>
<ModuleDefinition xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:schemaLocation="luna:schema ../../PartSyncSchema.xsd">
	<Fields>
		<FieldDefinition>
			<FieldName>cycleStartTime</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>progress</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>lastAttempt</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>inputEfficiency</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>outputEfficiency</FieldName>
		</FieldDefinition>
	</Fields>
</ModuleDefinition>

=== TheXankriegor/LunaCompat/LunaCompat/XML_COMPAT/InterstellarFuelSwitch/InterstellarFuelSwitch.xml
<?xml version="1.0"?>
<ModuleDefinition xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:schemaLocation="luna:schema ../../PartSyncSchema.xsd">
	<Fields>
		<FieldDefinition>
			<FieldName>selectedTankSetup</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>configuredAmounts</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>configuredFlowStates</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>storedFactorMultiplier</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>storedSurfaceMultiplier</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>storedVolumeMultiplier</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>baseMassMultiplier</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>initialMassMultiplier</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>dryMass</FieldName>
		</FieldDefinition>
	</Fields>
	<Methods>
		<MethodDefinition>
			<MethodName>ContextMenuDetach</MethodName>
		</MethodDefinition>
	</Methods>
</ModuleDefinition>
