=== TheXankriegor/LunaCompat/LunaCompat/PartSyncSchema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="ModuleDefinition">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="1" name="Fields">
					<xs:complexType>
						<xs:sequence>
							<xs:element maxOccurs="unbounded" name="FieldDefinition">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="FieldName" >
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:pattern value="^(?!\s*$).+" />
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element minOccurs="0" name="MaxIntervalInMs" type="xs:string" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
					<xs:unique name="UniqueFieldName">
						<xs:selector xpath="FieldDefinition" />
						<xs:field xpath="FieldName" />
					</xs:unique>
				</xs:element>
				<xs:element minOccurs="0" maxOccurs="1" name="Methods">
					<xs:complexType>
						<xs:sequence>
							<xs:element maxOccurs="unbounded" name="MethodDefinition">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="MethodName" >
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:pattern value="^(?!\s*$).+" />
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element minOccurs="0" name="MaxIntervalInMs" type="xs:string" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
					<xs:unique name="UniqueMethodName">
						<xs:selector xpath="MethodDefinition" />
						<xs:field xpath="MethodName" />
					</xs:unique>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
		
	</xs:element>
</xs:schema>

=== TheXankriegor/LunaCompat/LunaCompat/XML_COMPAT/Sandcastle/WBIShipbreaker.xml
<?xml version="1.0"?>
<ModuleDefinition xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:schemaLocation="luna:schema ../../PartSyncSchema.xsd">
	<Fields>
		<FieldDefinition>
			<FieldName>vesselCaptureEnabled</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>lastUpdateTime</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>currentJob</FieldName>
		</FieldDefinition>
	</Fields>
	<Methods>
		<MethodDefinition>
			<MethodName>ToggleActiveState</MethodName>
		</MethodDefinition>
	</Methods>
</ModuleDefinition>

=== TheXankriegor/LunaCompat/LunaCompat/XML_COMPAT/StationPartsExpansionRedux/ModuleDeployableCentrifuge.xml
<?xml version="1.0"?>
<ModuleDefinition xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:schemaLocation="luna:schema ../../PartSyncSchema.xsd">
	<Fields>
		<FieldDefinition>
			<FieldName>Rotating</FieldName>
		</FieldDefinition>
	</Fields>
	<Methods>
		<MethodDefinition>
			<MethodName>EventStartSpin</MethodName>
		</MethodDefinition>
		<MethodDefinition>
			<MethodName>EventStopSpin</MethodName>
		</MethodDefinition>
	</Methods>
</ModuleDefinition>

=== TheXankriegor/LunaCompat/LunaCompat/XML_COMPAT/ProceduralParts/ProceduralShapePolygon.xml
<?xml version="1.0"?>
<ModuleDefinition xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:schemaLocation="luna:schema ../../PartSyncSchema.xsd">
	<Fields>
		<FieldDefinition>
			<FieldName>cornerCount</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>diameter</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>length</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>OuterDiameter</FieldName>
		</FieldDefinition>
	</Fields>
</ModuleDefinition>

=== TheXankriegor/LunaCompat/LunaCompat/XML_COMPAT/Interstellar/FNGeneratorAdapterVariable.xml
<?xml version="1.0"?>
<ModuleDefinition xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:schemaLocation="luna:schema ../../PartSyncSchema.xsd">
	<Fields>
		<FieldDefinition>
			<FieldName>powerGeneratorPowerInput</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>powerGeneratorPowerOutput</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>last_active_time</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>initialMaxBufferSize</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>initialInputAmount</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>initialOutputAmount</FieldName>
		</FieldDefinition>
	</Fields>
</ModuleDefinition>

=== TheXankriegor/LunaCompat/LunaCompat/XML_COMPAT/WildBlueTools/WBIAstroTank.xml
<?xml version="1.0"?>
<ModuleDefinition xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:schemaLocation="luna:schema ../../PartSyncSchema.xsd">
	<Fields>
		<FieldDefinition>
			<FieldName>originalMass</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>previousMass</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>currentStorageCapacity</FieldName>
		</FieldDefinition>
	</Fields>
	<Methods>
		<MethodDefinition>
			<MethodName>SetObjectResources</MethodName>
		</MethodDefinition>
	</Methods>
</ModuleDefinition>

=== TheXankriegor/LunaCompat/LunaCompat/XML_COMPAT/ProceduralParts/TankContentSwitcher.xml
<?xml version="1.0"?>
<ModuleDefinition xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:schemaLocation="luna:schema ../../PartSyncSchema.xsd">
	<Fields>
		<FieldDefinition>
			<FieldName>tankVolume</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>mass</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>tankType</FieldName>
		</FieldDefinition>
	</Fields>
	<Methods>
		<MethodDefinition>
			<MethodName>OnPartVolumeChanged</MethodName>
		</MethodDefinition>
	</Methods>
</ModuleDefinition>

=== TheXankriegor/LunaCompat/LunaCompat/XML_COMPAT/KerbalActuators/WBIServoManager.xml
<?xml version="1.0"?>
<ModuleDefinition xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:schemaLocation="luna:schema ../../PartSyncSchema.xsd">
	<Fields>
		<FieldDefinition>
			<FieldName>managerState</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>sequenceID</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>snapshotID</FieldName>
		</FieldDefinition>
	</Fields>
</ModuleDefinition>

=== TheXankriegor/LunaCompat/LunaCompat/XML_COMPAT/Interstellar/EngineECU2.xml
<?xml version="1.0"?>
<ModuleDefinition xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:schemaLocation="luna:schema ../../PartSyncSchema.xsd">
	<Fields>
		<FieldDefinition>
			<FieldName>selectedFuel</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>IsEnabled</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>Launched</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>hideEmpty</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>selectedTank</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>selectedTankName</FieldName>
		</FieldDefinition>
	</Fields>
</ModuleDefinition>
