=== TheXankriegor/LunaCompat/LunaCompat/PartSyncSchema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="ModuleDefinition">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="1" name="Fields">
					<xs:complexType>
						<xs:sequence>
							<xs:element maxOccurs="unbounded" name="FieldDefinition">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="FieldName" >
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:pattern value="^(?!\s*$).+" />
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element minOccurs="0" name="MaxIntervalInMs" type="xs:string" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
					<xs:unique name="UniqueFieldName">
						<xs:selector xpath="FieldDefinition" />
						<xs:field xpath="FieldName" />
					</xs:unique>
				</xs:element>
				<xs:element minOccurs="0" maxOccurs="1" name="Methods">
					<xs:complexType>
						<xs:sequence>
							<xs:element maxOccurs="unbounded" name="MethodDefinition">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="MethodName" >
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:pattern value="^(?!\s*$).+" />
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element minOccurs="0" name="MaxIntervalInMs" type="xs:string" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
					<xs:unique name="UniqueMethodName">
						<xs:selector xpath="MethodDefinition" />
						<xs:field xpath="MethodName" />
					</xs:unique>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
		
	</xs:element>
</xs:schema>

=== TheXankriegor/LunaCompat/LunaCompat/XML_COMPAT/KerbalPlanetaryBaseSystems/ModuleKPBSConverter.xml
<?xml version="1.0"?>
<ModuleDefinition xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:schemaLocation="luna:schema ../../PartSyncSchema.xsd">
	<Fields>
		<FieldDefinition>
			<FieldName>productionSpeed</FieldName>
			<MaxIntervalInMs>250</MaxIntervalInMs>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>dumpOxygen</FieldName>
			<MaxIntervalInMs>250</MaxIntervalInMs>
		</FieldDefinition>
	</Fields>
</ModuleDefinition>

=== TheXankriegor/LunaCompat/LunaCompat/XML_COMPAT/InfernalRobotics/ModuleIRVariant.xml
<?xml version="1.0"?>
<ModuleDefinition xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:schemaLocation="luna:schema ../../PartSyncSchema.xsd">
	<Fields>
		<FieldDefinition>
			<FieldName>variantIndex</FieldName>
			<MaxIntervalInMs>250</MaxIntervalInMs>
		</FieldDefinition>
	</Fields>
	<Methods>
		<MethodDefinition>
			<MethodName>ActivateEvent</MethodName>
		</MethodDefinition>
	</Methods>
</ModuleDefinition>

=== TheXankriegor/LunaCompat/LunaCompat/XML_COMPAT/Interstellar/AlcubierreDrive.xml
<?xml version="1.0"?>
<ModuleDefinition xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:schemaLocation="luna:schema ../../PartSyncSchema.xsd">
	<Fields>
		<FieldDefinition>
			<FieldName>IsEnabled</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>IsCharging</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>existing_warp_speed</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>selected_factor</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>target_factor</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>isupgraded</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>serialisedwarpvector</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>spaceSafetyDistance</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>antigravityPercentage</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>matchExitToDestinationSpeed</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>maximizeWarpSpeed</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>holdAltitude</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>IsSlave</FieldName>
		</FieldDefinition>
	</Fields>
	<Methods>
		<MethodDefinition>
			<MethodName>StartCharging</MethodName>
		</MethodDefinition>
		<MethodDefinition>
			<MethodName>StopCharging</MethodName>
		</MethodDefinition>
		<MethodDefinition>
			<MethodName>ActivateWarpDrive</MethodName>
		</MethodDefinition>
		<MethodDefinition>
			<MethodName>DeactivateWarpDrive</MethodName>
		</MethodDefinition>
		<MethodDefinition>
			<MethodName>ReduceWarpPower</MethodName>
		</MethodDefinition>
		<MethodDefinition>
			<MethodName>RetrofitDrive</MethodName>
		</MethodDefinition>
	</Methods>
</ModuleDefinition>

=== TheXankriegor/LunaCompat/LunaCompat/XML_COMPAT/SystemHeat/ModuleSystemHeatCryoTank.xml
<?xml version="1.0"?>
<ModuleDefinition xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:schemaLocation="luna:schema ../../PartSyncSchema.xsd">
	<Fields>
		<!-- LastUpdateTime is a per-physics-tick simulation clock: it changes every FixedUpdate,
		     so it can never be quieted by a throttle and just floods the log/network. It is still
		     carried by LMP's periodic full-protovessel sync for load-time catch-up, so it is
		     intentionally not synced as an incremental field. -->
		<FieldDefinition>
			<FieldName>CoolingAllowed</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>CoolingEnabled</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>BoiloffOccuring</FieldName>
		</FieldDefinition>
	</Fields>
	<Methods>
		<MethodDefinition>
			<MethodName>Enable</MethodName>
		</MethodDefinition>
		<MethodDefinition>
			<MethodName>Disable</MethodName>
		</MethodDefinition>
	</Methods>
</ModuleDefinition>

=== TheXankriegor/LunaCompat/LunaCompat/XML_COMPAT/WildBlueTools/WBIBallastTank.xml
<?xml version="1.0"?>
<ModuleDefinition xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:schemaLocation="luna:schema ../../PartSyncSchema.xsd">
	<Fields>
		<FieldDefinition>
			<FieldName>tankType</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>ventState</FieldName>
		</FieldDefinition>
	</Fields>
	<Methods>
		<MethodDefinition>
			<MethodName>ToggleTankType</MethodName>
		</MethodDefinition>
		<MethodDefinition>
			<MethodName>FloodBallast</MethodName>
		</MethodDefinition>
		<MethodDefinition>
			<MethodName>VentBallast</MethodName>
		</MethodDefinition>
		<MethodDefinition>
			<MethodName>EmergencySurface</MethodName>
		</MethodDefinition>
		<MethodDefinition>
			<MethodName>CloseVents</MethodName>
		</MethodDefinition>
	</Methods>
</ModuleDefinition>

=== TheXankriegor/LunaCompat/LunaCompat/XML_COMPAT/KerbalActuators/WBILightController.xml
<?xml version="1.0"?>
<ModuleDefinition xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:schemaLocation="luna:schema ../../PartSyncSchema.xsd">
	<Fields>
		<FieldDefinition>
			<FieldName>ecRequired</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>red</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>green</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>blue</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>intensity</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>lightsOn</FieldName>
		</FieldDefinition>
	</Fields>
	<Methods>
		<MethodDefinition>
			<MethodName>ToggleLights</MethodName>
		</MethodDefinition>
	</Methods>
</ModuleDefinition>

=== TheXankriegor/LunaCompat/LunaCompat/XML_COMPAT/SpaceDust/ModuleSpaceDustScanner.xml
<?xml version="1.0"?>
<ModuleDefinition xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:schemaLocation="luna:schema ../../PartSyncSchema.xsd">
	<Fields>
		<FieldDefinition>
			<FieldName>Enabled</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>PowerCost</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>CurrentPowerConsumption</FieldName>
		</FieldDefinition>
	</Fields>
	<Methods>
		<MethodDefinition>
			<MethodName>EnableScanner</MethodName>
		</MethodDefinition>
		<MethodDefinition>
			<MethodName>DisableScanner</MethodName>
		</MethodDefinition>
	</Methods>
</ModuleDefinition>

=== TheXankriegor/LunaCompat/LunaCompat/XML_COMPAT/Interstellar/ThermalEngineController.xml
<?xml version="1.0"?>
<ModuleDefinition xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:schemaLocation="luna:schema ../../PartSyncSchema.xsd">
	<Fields>
		<FieldDefinition>
			<FieldName>storedAbsoluteFactor</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>storedFractionThermalReciever</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>IsEnabled</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>isupgraded</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>fuel_mode</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>isDeployed</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>animationStarted</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>exhaustAllowed</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>canActivatePowerSource</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>ispThrottle</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>fuelFlowThrottle</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>mhdPowerGenerationPercentage</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>sootAccumulationPercentage</FieldName>
		</FieldDefinition>
		<FieldDefinition>
			<FieldName>jetSpoolRatio</FieldName>
		</FieldDefinition>
	</Fields>
	<Methods>
		<MethodDefinition>
			<MethodName>NextPropellant</MethodName>
		</MethodDefinition>
		<MethodDefinition>
			<MethodName>PreviousPropellant</MethodName>
		</MethodDefinition>
		<MethodDefinition>
			<MethodName>RetrofitEngine</MethodName>
		</MethodDefinition>
	</Methods>
</ModuleDefinition>
